apiVersion: v1
kind: PersistentVolume
#这里定义的是k8s有哪些volume
metadata:
  name: my-local-pv
  labels:
    type: local
spec:
  #pvc中会根据这个名字找到该pv
  storageClassName: manual
  #容量
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    #宿主机存储的目录
    path: "/mnt/data"
